name: Publish package 📦

on:
  release:
    types: [published]
  push:
    tags:
      - "*"

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn rollup
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
