name: Publish package 📦
on:
  release:
    types: [published]
  push:
    tags:
      - "*"

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}